# Generated by Django 5.0.2 on 2024-02-16 11:35

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('type_of_body', models.CharField(choices=[('SEDAN', 'Седан'), ('HATCHBACK', 'Хетчбек'), ('UNIVERSAL', 'Универсал'), ('CROSSOVER', 'Кроссовер'), ('SUV', 'Внедорожник'), ('CABRIOLET', 'Кабриолет')], max_length=15, null=True, verbose_name='Тип кузова')),
                ('transmission', models.CharField(choices=[('MECHANICS', 'Механика'), ('AUTOMAT', 'Автомат')], max_length=15, null=True, verbose_name='Коробка передач')),
                ('wheel', models.CharField(choices=[('LEFT', 'Левый'), ('RIGTH', 'Правый')], max_length=10, null=True, verbose_name='Руль')),
                ('color', models.CharField(choices=[('BLACK', 'Черный'), ('WHITE', 'Белый'), ('BROWN', 'Коричневый'), ('SILVER', 'Серебристый'), ('GREEN', 'Зеленый'), ('RED', 'Красный'), ('YELLOW', 'Желтый')], max_length=50, null=True, verbose_name='Цвет')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='auto_photos/')),
                ('location', models.CharField(max_length=100, null=True, verbose_name='локация')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('ranting', models.CharField(choices=[('FROM 6 TO 24 HOURS', 'От 6 до 24 часов'), ('FROM 1 TO 7 DAYS', 'От 1 до 7 дней'), ('FROM 1 WEEK TO MONTH', 'От 1 недели до месяца')], max_length=60, null=True, verbose_name='аренда')),
                ('body', models.TextField(null=True, verbose_name='СОДЕРЖИМОЕ')),
                ('number', models.CharField(null=True, verbose_name='Номер телефона')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.category')),
            ],
        ),
    ]
